name: llm-gym
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - cached-property=1.5.2
  - cffi=1.15.1
  - chardet=4.0.0
  - comm=0.1.2
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - frozenlist=1.3.3
  - hdf5=1.10.6
  - idna=3.4
  - importlib_metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.10
  - packaging=23.1
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - ale-py==0.8.1
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - aquarel==0.0.5
      - attrs==23.1.0
      - box2d-py==2.3.5
      - cachetools==5.3.1
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - dataclasses-json==0.5.14
      - distro==1.8.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.0
      - filelock==3.12.3
      - fonttools==4.40.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - greenlet==2.0.2
      - grpcio==1.57.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - h5py==3.9.0
      - httpcore==1.0.2
      - httpx==0.25.2
      - huggingface-hub==0.16.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - langchain==0.0.270
      - langsmith==0.0.25
      - llvmlite==0.40.1
      - logger==1.4
      - loguru==0.7.0
      - markdown==3.4.4
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.7.1
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - numba==0.57.1
      - numexpr==2.8.5
      - oauthlib==3.2.2
      - openai==0.27.8
      - pandas==2.0.3
      - pathtools==0.1.2
      - pillow==9.5.0
      - protobuf==3.19.6
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.11
      - pydantic-core==2.6.1
      - pygame==2.1.0
      - pyparsing==3.0.9
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.3.3
      - seaborn==0.13.0
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - sqlalchemy==2.0.20
      - swig==4.1.1
      - tenacity==8.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.2.0
      - tiktoken==0.4.0
      - timeout-decorator==0.5.0
      - tokenizers==0.13.3
      - tqdm==4.65.0
      - transformers==4.30.2
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - v==1
      - wandb==0.15.5
      - werkzeug==2.3.7
      - win32-setctime==1.1.0
      - yarl==1.9.2
      - zipp==3.15.0
      - git+ssh://git@github.com/hyyh28/atari-representation-learning.git